/// @description States List
// You can write your code in this editor

IDLE = "IDLE";
RUN_RIGHT = "RUN_RIGHT";
RUN_LEFT = "RUN_LEFT";
FALL_LEFT = "FALL_LEFT";
FALL_RIGHT = "FALL_RIGHT";
ATTACK_LEFT1 = "ATTACK_LEFT1";
ATTACK_LEFT2 = "ATTACK_LEFT2";
ATTACK_LEFT3 = "ATTACK_LEFT3";
ATTACK_RIGHT1 = "ATTACK_RIGHT1";
ATTACK_RIGHT2 = "ATTACK_RIGHT2";
ATTACK_RIGHT3 = "ATTACK_RIGHT3";
LASER_ATTACK_LEFT = "LASER_ATTACK_LEFT";
LASER_ATTACK_RIGHT = "LASER_ATTACK_RIGHT";
DASH_ATTACK_LEFT = "DASH_ATTACK_LEFT";
DASH_ATTACK_RIGHT = "DASH_ATTACK_RIGHT";
POUND_RIGHT = "POUND_RIGHT";
POUND_LEFT = "POUND_LEFT";
JUMP1_LEFT = "JUMP1_LEFT";
JUMP1_RIGHT = "JUMP1_RIGHT";
JUMP2_RIGHT = "JUMP2_RIGHT";
JUMP2_LEFT = "JUMP2_LEFT";
